# meta_product_name: "Product Name"
meta_title: "Transmission universelle de patrimoine | Simulateur"
meta_description: "Un simulateur pour calculer les dates clés de vos opérations de transmission universelle de patrimoine (TUP) : date de publication, période d'opposition des créanciers, date de réalisation / date d'effet"
meta_image: "/src/assets/images/tup.png"
twitter_account: "@alexplatteeuw"   # required for Twitter Cards
